### ISSUE TITLE
Headless emulator

### ISSUE THREAD

**Issue by allxone** [astro-pi/python-sense-emu#28]
Hi,
I'm using your great emulator to test a ROS package to interact with the SenseHat. It really helps both development and testing avoiding much of the mock stuff.

I'm working with Docker to eventually deploy the application via Balena Cloud. Testing would be much easier if I could start the emulator without the GUI and all the related system dependencies. Do you have any suggestion about doing this?

Thanks,
Stefano

**Comment by waveform80** [comment]
It should be possible to make a headless/mock server relatively easily. A long-time goal of mine (when I get a spare moment) has been to make a TUI/curses front end for the emulator. The emulator code itself is deliberately separate from the GUI for just this purpose, but that equally lends itself to making a programmatic / mock front end for it.

**Comment by waveform80** [comment]
Yes, `sense_play` is essentially what you're looking for provided you're happy with playing back a pre-recorded session. The intention is indeed to start `sense_rec`, then "do something" with the HAT (dropping it, swinging it round, breathing on it, etc.) so the results can be played back against a script later. I suppose you could even have something generate the recorded output and pipe it to `sense_play` to construct a headless emulator on the command line!

A bit of background: this was something I threw in as a last minute addition to the suite (it wasn't in the contract, hence why there's no fancy GUI for it or anything). Having had the idea though, we had a vague notion that it could be used in the Astro Pi mission, e.g. for recording readings from the IMU during a boost manoeuvre on the ISS which could then be played back by people entering the competition to test their entries against "real" data from the ISS (which they wouldn't otherwise have any chance of gathering or accurately simulating themselves).

Whether any such recordings were ever produced or are available, I've no idea. Be nice to get some examples to include in the suite, though!

The CSV conversion was largely thrown in for ease of debugging (so I could quickly dump a recording into something like veusz to graph it).

**Comment by allxone** [comment]
I finally ended up using **sense_play** to support tests via pre-recorded trace files I produced with **sense_rec** and an actual Sense HAT device.
You can find them [here](https://github.com/allxone/sensehat_ros/tree/master/test/resources)

Thanks,
Stefano
